### ISSUE TITLE
proposal: Add default set for operations

### ISSUE THREAD

**Issue by Xuanwo** [aos-dev/go-storage#170]
Allow user set storage class while init services.

**Comment by Xuanwo** [comment]
Maybe add `DefaultPair` struct?

**Comment by Xuanwo** [comment]
Let service store a slice of `Pair`, and merge with user input evey time parse input pairs?

**Comment by Prnyself** [comment]
See more details in [proposal: add default set for operations](https://github.com/aos-dev/specs/blob/master/rfcs/22-add-default-set-for-operations.md). 
Implemented by #504
