### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by OldSmokeGun** [aos-dev/go-storage#539]
缺少使用文档，不知道如何安装，如何使用

**Comment by Xuanwo** [comment]
只需要把这个库添加为项目依赖即可：

```
go get github.com/aos-dev/go-storage/v3
```

quick start 可以参见 https://github.com/aos-dev/go-storage#quick-start

我们现在正在写一些 example，可以关注一下我们的文档官网： https://aos.dev/docs/go-storage/index
