### ISSUE TITLE
Implement AOS-47: Additional Error Specification 

### ISSUE THREAD

**Issue by xxchan** [aos-dev/go-storage#558]
[rendered proposal](https://github.com/aos-dev/specs/blob/master/rfcs/47-additional-error-specification.md)

implement AOS-51 together https://github.com/aos-dev/specs/pull/51

- [x] update go-storage: https://github.com/aos-dev/go-storage/pull/555 https://github.com/aos-dev/go-storage/pull/564

go-service-*:

first update dependency: `go get -d github.com/aos-dev/go-storage/v3@master`

AOS-47:
- Turn ad-hoc string errors into defined errors: check `rg "(fmt.Errorf)|errors\.New"`
- Turn SDK errors into `fmt.Errorf("%w, %v", services.ErrUnexpected, err)`
- Return error structs instead of pointers: 
  - `rg -l "Error" | xargs sed -i 's/&\(.*\)Error/\1Error/g'`
  - `rg -l "Error" | xargs sed -i 's/New\(.*\)Error(\(.*\))/\1Error{\2}/g'`
- Check naming convention

AOS-51:
- use `errorCode` : `rg -l "errors\.New" | xargs sed -i 's/errors\.New/services.NewErrorCode/g'`
- check `AosError` in `formatError`: add this
```go
	if _, ok := err.(services.AosError); ok {
		return err
	}
```
- add `formatError` in `InitError`'s `Err` field: 
  - update `newServicerAndStorager`
  - `rg -l InitError | xargs sed -i 's/InitError\(.*\)Err: err/InitError\1Err: formatError(err)/g'`
---

- [x] azblob
- [x] cos
- [x] dropbox
- [x] fs
- [x] gcs
- [x] kodo
- [x] oss
- [x] qingstor
- [x] s3
- [x] uss

**Comment by Xuanwo** [comment]
Please also update [go-service-example](https://github.com/aos-dev/go-service-example)

**Comment by Xuanwo** [comment]
Let's add a doc about error handling in go-storage? Tell the user what's our design and how could they use it.
